apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: appset
    repoURL: https://github.com/acuD1/test-appset.git
    directory:
      recurse: true
  syncPolicy:
    automated: {}
